### ISSUE TITLE
HTTP 403 when searching

### ISSUE THREAD

**Issue by buhtz** [sigurdga/maps#13]
Using `openstreetmap-client 14.03.1` on Siduction GNU/LInux (Debian GNU/Linux **unstable**).

When I search something I got this output on the commandline

```
Traceback (most recent call last):
  File "/usr/share/openstreetmap-client/maps/map_window.py", line 467, in on_search_clicked
    searcher.search(text)
  File "/usr/share/openstreetmap-client/maps/searcher.py", line 163, in search
    response = urllib2.urlopen(req).read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden

```

**Comment by buhtz** [comment]
Also tracked on Debian
[openstreetmap-client: Search functionality fails - HTTP Error 403 Forbidden](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819109)
